name: Build CodeConverter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
 build:
    runs-on: windows-latest
    env:
      BuildVersion: '8.3.1'
      BuildPlatform: Any CPU
      BuildTarget: Release
    steps:
    - uses: actions/checkout@v2
    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        projectFilter: '**/CodeConverter.csproj'
        version: ${{ env.BuildVersion }}.${{ github.run_number }}
        assemblyVersion: ${{ env.BuildVersion }}.${{ github.run_number }}
        fileVersion: ${{ env.BuildVersion }}.${{ github.run_number }}
    - name: Setup .NET for main build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
       vs-version: '[16.6,)'
    - name: Publish the application
      run: dotnet publish CodeConverter.sln /p:Configuration=$env:BuildTarget /p:Platform=$env:BuildPlatform
    - name: Execute unit tests
      run: dotnet test $env:Tests1
      env:
        Tests1: Tests/bin/${{ env.BuildTarget }}/ICSharpCode.CodeConverter.Tests.dll
    - name: Pack
      run:  dotnet pack CodeConverter/CodeConverter.csproj -c $env:BuildTarget
    - name: Upload NuGet package
      uses: actions/upload-artifact@v2
      with:
        name: ICSharpCode.CodeConverter.${{ env.BuildVersion }}.nupkg
        path: CodeConverter/bin/${{ env.BuildTarget }}/ICSharpCode.CodeConverter.*.nupkg
    - name: Upload VSIX
      uses: actions/upload-artifact@v2
      with:
        name: ICSharpCode.CodeConverter.VsExtension.${{ env.BuildVersion }}.vsix
        path: Vsix/bin/${{ env.BuildTarget }}/ICSharpCode.CodeConverter.VsExtension.vsix
    - name: Upload code conv tool
      uses: actions/upload-artifact@v2
      with:
        name: ICSharpCode.CodeConverter.CodeConv.${{ env.BuildVersion }}.nupkg
        path: CommandLine/CodeConv/bin/${{ env.BuildTarget }}/ICSharpCode.CodeConverter.CodeConv.*.nupkg
    - name: Upload website
      uses: actions/upload-artifact@v2
      with:
        name: ICSharpCode.CodeConverter.Web.${{ env.BuildVersion }}.zip
        path: Web/bin/${{ env.BuildTarget }}/publish/
    - name: Upload Azure function
      uses: actions/upload-artifact@v2
      with:
        name: ICSharpCode.CodeConverter.Func.${{ env.BuildVersion }}.zip
        path: Web/bin/${{ env.BuildTarget }}/
